### ISSUE TITLE
Send log out to Discourse

### ISSUE THREAD

**Issue by stevelacey** [spinen/laravel-discourse-sso#19]
This library works great, thanks!

I saw your TODO:

- Send log out to Discourse when disabling/deleting the user

Am I right in thinking this means syncing logout isn’t supported at all?

I have an existing `/logout` that needs to apply to Discourse — so that users can log out app-side.

Any approach recommendations for that?

The Discourse-side logout is easily enough catered for by setting the logout redirect in Discourse, but it looks like Discourse logs out via an auth’d `DELETE /*/session` which I get a 403 for currently if I ajax it app-side 😕

**Comment by stevelacey** [comment]
I put a solution together based on the Discourse recommended approach described at https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045#heading--logoff:

```php
<?php

namespace App\Listeners;

use GuzzleHttp;
use Illuminate\Auth\Events\Logout;
use Illuminate\Contracts\Queue\ShouldQueue;

class LogoutDiscourseUser implements ShouldQueue
{
    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handleLogout(Logout $event)
    {
        if (!$event->user) {
            return;
        }

        $client = new GuzzleHttp\Client([
            'base_uri' => config('services.discourse.url'),
            'headers' =>  [
                'Api-Key' => config('services.discourse.api.key'),
                'Api-Username' => config('services.discourse.api.user'),
            ],
        ]);

        $user = json_decode($client->get("users/by-external/{$event->user->id}.json")->getBody())->user;

        $client->post("admin/users/{$user->id}/log_out");
    }
}
```

A Discourse API key (and user) is required, these can be grabbed from the Discourse admin.

**Comment by ssfinney** [comment]
Hi @stevelacey! You were correct, syncing logouts isn't currently supported. I think your approach is good, although I would like to avoid using Guzzle here (probably unavoidable though, since the `SSOHelper` doesn't give us anything to use to do this).

Thanks for putting that code together! Here's a list of what we would want to add to the package to support this:

- Add Discourse API key as a config value
- New method in `SSOController.php` for `logout()` with your code above
- A helper method to get the user's information from Discourse like you're doing above
- Some tests to capture the use case of logging the user out

cc @jimmypuckett if he has anything to add or change from this list.

@stevelacey Feel free to make a PR for this, but either way thanks for the snippet 😄  We can work on this when we get a sec.

**Comment by jimmypuckett** [comment]
@stevelacey Thanks so much for digging into this!

I agree with @ssfinney that we need to add the api key stuff to the docs for the config with an env., but I am not sure that I understand the controller logout stuff as this seems perfect for a Listener as you have it.  I would see a Listenser with a `handle` method & then constructor inject the `Guzzel` to allow of easier testing.

@stevelacey do you fell like making a PR or do you want us to run with it?

**Comment by stevelacey** [comment]
I'll let you run with it 🙏 feel free to use the above as you see fit.

As @jimmypuckett said, not sure why you'd want a controller method, the listener binds any Laravel logout to a Discourse logout, and doesn't require the user to be routed any particular way. The listener supports a Laravel logout (or in my case, Laravel Spark), a Laravel Nova logout, any, it syncs everything up nicely.

**Note:** you may also want to document that setting the Discourse logout redirect setting to Laravel's `/logout` is the recommended way to sync a `Discourse -> Laravel` logout – and that matching the session expiry up is probably advisable.

**Comment by ssfinney** [comment]
OK, done and pushed under release `2.4.0`
